### ISSUE TITLE
Item check box overlays icon

### ISSUE THREAD

**Issue by ottogunter** [incognito1234/Keepass-Custom-Icon-Dashboarder#14]
Regardless of what window size I set, or when I re-size the "Icon" column, every icon is obscured by it's own item check box.  It is not due to my screen resolution (3840 x 2160), I have tried others and get the same result. Just downloaded latest v1.3.0.
![Screenshot1](https://user-images.githubusercontent.com/42825620/232611648-26a13f04-9b33-4d53-b5ab-695a99dd5c6f.jpg)
![Screenshot2](https://user-images.githubusercontent.com/42825620/232611698-93048dec-bb19-4f15-9f93-bc28358e48e0.jpg)

**Comment by incognito1234** [comment]
Hi,
Could you indicate the version of KeePass version and your OS version ?
Does this issue exist with the previous version of KPCID (v1.2.0) ?
Thank you

**Comment by ottogunter** [comment]
Thanks for the quick response! I'm on the latest Win 11 (22H2 build 22621.1555) and the latest KeePass v2.53.1). I've rolled KPCID back to v1.2.0 and the same problem exists with icon overlays as I've reported for 1.3.0 (see below). Truth be told, I hadn't used KPCID for a while so hadn't noticed the problem earlier.

Please let me know if you need more info.
_________
horst.

***@***.***

**Comment by incognito1234** [comment]
I have just checked on a Win 11 workstation with the last version of KeePass (v2.53.1) and I was not able to reproduce the issue.
It could be an incompatibility with another plugin or a customization of apparence (Screenshots seem to indicate that a dark theme is used). Please try to another machine/OS.
Cheers

**Comment by ottogunter** [comment]
![image](https://user-images.githubusercontent.com/42825620/234085205-97c0d15b-fafb-4329-9486-42d844cdeb69.png)
All is fine. You were correct, icons are displayed properly once I remove the dark theme plugin KeeTheme.
