### ISSUE TITLE
Version 1.2.0 breaks compatibility with linux

### ISSUE THREAD

**Issue by Sanaki** [incognito1234/KeePass-Custom-Icon-Dashboarder#2]
Strange bug, but it claims it needs a newer .NET framework when no such thing exists. The same issue was addressed in dlech/KeeAgent#271 as well, in case you'd like to review the solution there. For some reason the version check is being a bit wonky.

**Comment by incognito1234** [comment]
Hi Sanaki,

Check of version with mono seems to be a quirk.
Please try this version of plugin - to be unzipped - and give a feedback.
[CustomIconDashboarder.zip](https://github.com/incognito1234/KeePass-Custom-Icon-Dashboarder/files/3752943/CustomIconDashboarder.zip)

Thank you,

Jareth

**Comment by Sanaki** [comment]
That version works perfectly. Thanks for the quick fix.

**Comment by incognito1234** [comment]
Thanks for your feedback. I will include this modification in the next version.
