### ISSUE TITLE
[Waiting on feedback]Crashes on malformed URLs [v1.2]

### ISSUE THREAD

**Issue by rasa** [incognito1234/KeePass-Custom-Icon-Dashboarder#3]
Without a message. Is there any way to turn on debugging to see where it’s crashing?

**Comment by rasa** [comment]
I had a malformed URL. When I removed the value, it worked fine. Sorry for the noise. Great program!

**Comment by incognito1234** [comment]
Hello Rasa,
Thank you for your report.
Crash is not a relevant behavior even if all the stars are not perfectly aligned. So I would be interested in the malformed URL that turns the plugin into a bomb.

**Comment by rasa** [comment]
I did some more testing, and it’s either a “URL” that’s actually a Windows path name (C:\path\to\ex.kdbx), as the [KeeAutoExec](https://keepass.info/plugins.html#keeautoexec) plugin uses the URL field in this way, or it’s a URL without the scheme (10.0.0.2) as that’s  an acceptable URL for the [KeePassRDP](https://keepass.info/plugins.html#kprdp) plugin.

When I included these “bogus” URL entries, KeePass v2.43 (and [CID v1.20](https://github.com/incognito1234/KeePass-Custom-Icon-Dashboarder/releases/download/v1.2.0/CustomIconDashboarder.plgx)) quietly aborts during the download process. When I unchecked these entries, it ran to completion fine. I hope that helps! 

Thanks for a *great* plugin!

**Comment by rasa** [comment]
I’m gonna reopen this as you may have missed my last comment. Please close it if you are unable to duplicate the issue.

**Comment by tjmchenry** [comment]
An entry with `http://` for the URL will cause this crash.

**Comment by chtof** [comment]
An entry with `http;//` for example (typing error) also cause a crash.

**Comment by stonecrusher** [comment]
The crash also occurs if you have set a reference instead of an URL. Like `{REF:A@I:5F00943CB08BA743A553AF11450C9687}`.
You can set them in the "Edit entry" window when clicking "Tools" on the bottom left.
KeePass 2.5.2 (x64) with plugin ver.1.2

**Comment by ploedman** [comment]
I also have an issues with Crashing while setting the Icons which he Downloaded, also it crashes when mass deleting Icons.

**Comment by incognito1234** [comment]
Hi,
The last release should solve this issue.
Please try it and give a feedback.
Thanks

**Comment by stonecrusher** [comment]
Works here, no more crash. It says "Malformed url" in the "New size" column. Thank you!

    KeePass 2.53.1 (64-Bit) on Win10
    KeePass Custom Icon Dashboarder Version 1.3
