### ISSUE TITLE
Invalid URI crash

### ISSUE THREAD

**Issue by thakyZ** [incognito1234/KeePass-Custom-Icon-Dashboarder#5]
I had an entry that's url was `https://*.example.com/`. When your plugin went to try to fetch the icon from that site, it couldn't handle the asterisks in the url and ended up closing out the entirety of keepass. Could you possibly add a check for the url being valid? Thanks.

**Comment by rasa** [comment]
See #3.

**Comment by thakyZ** [comment]
Ah thanks.
