### ISSUE TITLE
Crash when url field has invalid content

### ISSUE THREAD

**Issue by icaptnbob** [incognito1234/KeePass-Custom-Icon-Dashboarder#6]
Hi.
Great app, but it crashes when the URL field has invalid content.
E.g. I had this:  www.netgear.com  & genie.netgear.com Marketplace readycloud.netgear.com
Instead of complaining or showing a message, it simply closes, loosing any changes made since.

**Comment by rasa** [comment]
@icaptnbob See #3

**Comment by icaptnbob** [comment]
Noted. I'll close this ticket and watch the other.
Thanks :-)
